name: CI/CD Pipeline
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        run: docker build -f Dockerfile.dev -t docker-react .
      - name: Run tests
        run: docker run docker-react npm run test -- --watchAll=false

  deploy:
    needs: test
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Install EB CLI
        run: pip install awsebcli
      - name: Build production Docker image
        run: docker build -t docker-react-prod .
      - name: Deploy to Elastic Beanstalk
        run: |
          eb init -p docker docker-frontend --region ${{ secrets.AWS_REGION }} --platform "Docker"
          eb use Docker-frontend-env  # Имя твоего environment
          eb deploy
